package com.davecoss.android.genericserver;

public class EmptyRequest extends HTTPError
{

    /**
     * UID Generated by Eclipse
     */
    private static final long serialVersionUID = 6624794259069051686L;
    
    public EmptyRequest()
    {
	super();
    }
    
    public EmptyRequest(String message)
    {
	super(message);
    }
    
    public EmptyRequest(String message, Throwable throwable)
    {
	super(message, throwable);
    }
}
