package com.davecoss.android.genericserver;

public class HTTPError extends Exception {
	/**
	 * UID Generated by Eclipse
	 */
	private static final long serialVersionUID = -6939556483195479424L;

	public HTTPError() {
		super();
	}

	public HTTPError(String message) {
		super(message);
	}

	public HTTPError(String message, Throwable throwable) {
		super(message, throwable);
	}
}
