package com.davecoss.android.genericserver;

public class InvalidPostData extends HTTPError {

	
	/**
	 * UID generated by Eclipse
	 */
	private static final long serialVersionUID = -7421728875329248108L;

	public InvalidPostData() {
		super();
	}

	public InvalidPostData(String message) {
		super(message);
	}

	public InvalidPostData(String message, Throwable throwable) {
		super(message, throwable);
	}
	
}

