package com.davecoss.android.genericserver;

public class InvalidRequestData extends HTTPError
{
    /**
     * UID Generated by Eclipse
     */
    private static final long serialVersionUID = -8945493902183733640L;
    
    public InvalidRequestData()
    {
	super();
    }
    
    public InvalidRequestData(String message)
    {
	super(message);
    }
    
    public InvalidRequestData(String message, Throwable throwable)
    {
	super(message, throwable);
    }
}

